# Generated by Django 5.2.5 on 2025-08-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options_alter_inscricao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='dados_adicionais',
        ),
        migrations.AddField(
            model_name='participante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
