# Generated by Django 5.2.5 on 2025-08-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_participante_dados_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback do participante sobre o evento', null=True, verbose_name='Feedback'),
        ),
    ]
