# Generated by Django 5.2.5 on 2025-08-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_inscricao_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='feedback',
            field=models.TextField(blank=True, help_text='Mensagem de feedback do participante.', null=True, verbose_name='Feedback'),
        ),
    ]
